name: Code Coverage

on:
  push:
    branches: [ main ]
    paths-ignore:
    - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
    - '**.md'

jobs:
  build-test-report:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [net6.0]

    env:
      OS: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore /p:ContinuousIntegrationBuild=true

    - name: Test ${{ matrix.version }}
      run: dotnet test --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

    - uses: codecov/codecov-action@v3.1.1
      with:
        env_vars: OS
        name: Code Coverage for ${{ matrix.os }}
        fail_ci_if_error: true
        verbose: true
